---
# Google Cloud Storage (GCS) Bucket

- name: SAP HANA Backint - Execute - Set fact for SID
  ansible.builtin.set_fact:
    passed_sap_hana_sid: "{{ sap_hana_sid }}"
  when: sap_hana_sid != "all"

# Set initial facts
- name: SAP HANA Backint - Setup - GCS - Set facts
  ansible.builtin.set_fact:
    sap_hana_backint_setup_backint_directory: "/usr/sap/{{ passed_sap_hana_sid }}/SYS/global/hdb/opt"
    passed_sap_hana_instance_nr: "{{ sap_hana_instance_nr_one[0] }}"

- name: SAP HANA Backint - Setup - GCS - Download hanacleaner.py
  ansible.builtin.get_url:
    url: https://github.com/chriselswede/hanacleaner/archive/refs/heads/master.zip
    dest: "/tmp/hanacleaner-master.zip"
    mode: '0440'

- name: SAP HANA Backint - Setup - GCS - Unpack hanacleaner.py
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/hanacleaner-master.zip"
    dest: "/tmp"

# Copy hanacleaner.py
- name: SAP HANA Backint - Setup - GCS - Copy hanacleaner.py to SAP HANA backint directory
  ansible.builtin.copy:
    src: "/tmp/hanacleaner-master/hanacleaner.py"
    dest: "{{ sap_hana_backint_setup_backint_directory }}/hanacleaner.py"
    mode: "0755"
    remote_src: true
  register: hdbbackint_hanacleaner

- name: SAP HANA Backint - Setup - GCS - Download temp dir
  ansible.builtin.tempfile:
    state: directory
    suffix: gcs_download
  register: gcs_download
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"

- name: SAP HANA Backint - Setup - GCS - Download Google Cloud Storage Backint agent for SAP HANA
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/cloudsapdeploy/backint-gcs/install.sh
    dest: "{{ gcs_download.path }}/gcs_backint_install.sh"
    mode: "0775"
  become_user: "{{ sap_hana_sid | lower }}adm"

- name: SAP HANA Backint - Setup - GCS - Execute install.sh (silent)
  ansible.builtin.shell: "{{ gcs_download.path }}/gcs_backint_install.sh"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  environment:
    SAPSYSTEMNAME: "{{ passed_sap_hana_sid }}"
# Add task to process /usr/sap/SID/SYS/global/hdb/opt/backint/backint-gcs/parameters.txt
# Use /templates/gcs_config.cfg
# catalog_backup_parameter_file /usr/sap/SID/SYS/global/hdb/opt/backint/backint-gcs/parameters-catalog.txt
# data_backup_parameter_file /usr/sap/SID/SYS/global/hdb/opt/backint/backint-gcs/parameters-data.txt
# log_backup_parameter_file  /usr/sap/SID/SYS/global/hdb/opt/backint/backint-gcs/parameters-log.txt
