---

- name: Prepare - Set function control facts
  ansible.builtin.set_fact:
    sap_type: "{{ function_list.sap_control_function_current.split('_')[0] | lower }}"
    funct_type: "{{ function_list.sap_control_function_current.split('_')[1] | lower }}"

- name: Prepare - Set header
  ansible.builtin.set_fact:
    sap_control_name_header: "{{ sap_type | upper }} {{ funct_type | capitalize }}"

- name: SAP Control
  vars:
    sap_control_execute_sid: "{{ item.SID }}"
    sap_control_execute_type: "{{ item.Type }}"
    sap_control_execute_instance_nr: "{{ item.NR }}"
    sap_control_execute_instance_type: "{{ item.InstanceType }}"
  ansible.builtin.include_tasks: "sapcontrol.yml"
  loop: "{{ sap_facts_register.ansible_facts.sap }}"
  when:
    - "item.InstanceType | lower == sap_type | lower"
