---
# This task requires the variables
# passed_sap_sid
# passed_sap_nr

# Check sapstartsrv
- name: SAPstartsrv - Check sapstartsrv
  ansible.builtin.shell: |
    source ~/.profile ; sapcontrol -nr {{ passed_sap_nr }} -function GetSystemInstanceList
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ passed_sap_sid | lower }}adm"
  ignore_errors: true
  register: check_sapstartsrv
  changed_when:
    - ('FAIL' in check_sapstartsrv.stdout)

# Check sapstartsrv
- name: SAPstartsrv - Restart sapstartsrv
  ansible.builtin.include_tasks: restart_sapstartsrv.yml
  when:
    - ('FAIL' in check_sapstartsrv.stdout)
